version: '3.9'
services:

  pg4:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: lismgmk2@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - common_network
    # ngrok:
  #   image: wernight/ngrok
  #   container_name: ngrok
  #   restart: unless-stopped
  #   command:
  #       - "ngrok"
  #       - "start"
  #       - "--all"
  #       - "--config"
  #       - "/etc/ngrok.yml"
  #   volumes:
  #       - ./ngrok.yml:/etc/ngrok.yml
  #   ports:
  #     - '4040:4040'
  #   depends_on:
  #     - n8n
  #   networks:
  #     - common_network

volumes:
  pgadmin-data:
    driver: local