version: 2
authtoken: 2db6S52EkC2YmVZkAZLGlI9slGM_3bz7zYjiHVguutbBdTtGN
tunnels:
  n8n:
    proto: http
    addr: browserless:3000
    # addr: n8n:5678
    host_header: rewrite
    # bind_tls: true
   