name: Deploy to development environment

on:
  push:
    branches: ['dev']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Deploy to VM
        run: |
          ssh lis@5.35.82.67 << EOF
            set -e            
            cd ${{ secrets.FOLDER }}
            git branch
            git checkout dev
            GIT_SSH_COMMAND="ssh -i ~/.ssh/${{ secrets.PATH_KEY }}" git pull
            docker compose down --volumes
            docker compose -f docker-compose.yml up --build -d
            docker system prune -af
