name: Deploy to development environment

on:
  push:
    branches: ['dev']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username:  ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e            
            cd ${{ secrets.FOLDER }}
            git branch
            git checkout dev
            GIT_SSH_COMMAND="ssh -i ~/.ssh/${{ secrets.PATH_KEY }}" git pull
            docker compose down --volumes
            docker compose -f docker-compose.yml up --build -d
            docker system prune -af

   